spring:
  application:
    name: zuul-server
server:
  port: 8866

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3333/eureka/  #前端就是http://localhost:8866/api-customer(服务ID)/api(路径) 调用即可