eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3333/eureka/
spring:
  application:
    name: api-customer
server:
  port: 7777

wallet:
  xmccb:
    platformNo: 123456
    gateway: http://baidu.com
    publicKeyString: jassslsdlfdnk